# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('edfR_rcpp_hello', PACKAGE = 'edfR')
}

timesTwo <- function(x) {
    .Call('edfR_timesTwo', PACKAGE = 'edfR', x)
}

edfTest <- function(filename) {
    .Call('edfR_edfTest', PACKAGE = 'edfR', filename)
}

